# Generated by Django 6.0 on 2026-04-18 13:23

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="KutumbaRequestLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("external_id", models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ("created_date", models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ("modified_date", models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ("deleted", models.BooleanField(db_index=True, default=False)),
                ("request_id", models.CharField(max_length=20)),
                ("response_id", models.CharField(blank=True, max_length=255, null=True)),
                ("rc_number", models.CharField(max_length=12)),
                ("success", models.BooleanField()),
                ("status_code", models.IntegerField()),
                ("status_text", models.CharField(max_length=255)),
                ("members", models.JSONField(default=list)),
                ("member_count", models.PositiveIntegerField(default=0)),
                ("error", models.TextField(blank=True, null=True)),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="kutumba_request_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "care_kutumba_request_log",
            },
        ),
    ]
