# Generated by Django 6.0 on 2026-04-18 19:41

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("care_kutumba", "0001_initial"),
        ("emr", "0077_tagconfig_metadata"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="KutumbaPatientLink",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("external_id", models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ("created_date", models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ("modified_date", models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ("deleted", models.BooleanField(db_index=True, default=False)),
                ("selected_member_index", models.PositiveIntegerField()),
                ("selected_member_data", models.JSONField(default=dict)),
                ("rc_number", models.CharField(max_length=12)),
                ("action", models.CharField(choices=[("create", "Create"), ("update", "Update")], max_length=20)),
                (
                    "patient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="kutumba_links",
                        to="emr.patient",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="kutumba_patient_links",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "request_log",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="patient_links",
                        to="care_kutumba.kutumbarequestlog",
                    ),
                ),
            ],
            options={
                "db_table": "care_kutumba_patient_link",
            },
        ),
    ]
